In [1]:
import tensorflow as tf
import numpy as np
import pandas as pd

In [2]:
data_df = pd.read_csv('Purchased.csv')

data_df.head()

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes

In [3]:
data_df['Salary'] = data_df['Salary'].fillna(value=63778)  #age 39

In [4]:
data_df['Age'] = data_df['Age'].fillna(value=39)  #age 39
data_df

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0  63778.0       Yes
5   France  35.0  58000.0       Yes
6    Spain  39.0  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [5]:
k = 0
for i in data_df["Country"]:
    if i == "Germany":
        data_df["Country"].loc[k] = 1
    elif i == "Spain":
        data_df["Country"].loc[k] = 2
    else:
        data_df["Country"].loc[k] = 3
    k += 1

C:\Users\SHANTANU\AppData\Local\Temp\ipykernel_52100\1067976761.py:8: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_df["Country"].loc[k] = 3
C:\Users\SHANTANU\AppData\Local\Temp\ipykernel_52100\1067976761.py:6: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_df["Country"].loc[k] = 2
C:\Users\SHANTANU\AppData\Local\Temp\ipykernel_52100\1067976761.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_df["Country"].loc[k] = 1


In [6]:
data_df

Country   Age   Salary Purchased
0       3  44.0  72000.0        No
1       2  27.0  48000.0       Yes
2       1  30.0  54000.0        No
3       2  38.0  61000.0        No
4       1  40.0  63778.0       Yes
5       3  35.0  58000.0       Yes
6       2  39.0  52000.0        No
7       3  48.0  79000.0       Yes
8       1  50.0  83000.0        No
9       3  37.0  67000.0       Yes

In [7]:
k = 0
for i in data_df["Purchased"]:
    if i == "Yes":
        data_df["Purchased"].loc[k] = 1
    elif i == "No":
        data_df["Purchased"].loc[k] = 0
    k += 1

C:\Users\SHANTANU\AppData\Local\Temp\ipykernel_52100\591928749.py:6: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_df["Purchased"].loc[k] = 0
C:\Users\SHANTANU\AppData\Local\Temp\ipykernel_52100\591928749.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_df["Purchased"].loc[k] = 1


In [46]:
data_df

Country   Age    Salary Purchased
0       1.0  0.88  0.867470         0
1  0.666667  0.54  0.578313         1
2  0.333333  0.60  0.650602         0
3  0.666667  0.76  0.734940         0
4  0.333333  0.80  0.768410         1
5       1.0  0.70  0.698795         1
6  0.666667  0.78  0.626506         0
7       1.0  0.96  0.951807         1
8  0.333333  1.00  1.000000         0
9       1.0  0.74  0.807229         1

In [41]:
data_df['Age'] = data_df['Age'] / max(data_df['Age'])

In [43]:
data_df['Salary'] = data_df['Salary'] / max(data_df['Salary'])

In [45]:
data_df['Country'] = data_df['Country'] / max(data_df['Country'])

In [9]:
data_df[['Country', 'Age', 'Salary']].shape

(10, 3)

In [73]:
model = tf.keras.Sequential(
    [tf.keras.layers.Dense(units=1, input_shape=[3]), tf.keras.layers.Dense(256, activation='relu'),
     tf.keras.layers.Dense(128, activation='sigmoid'), tf.keras.layers.Dense(1, activation='softmax')])

model.summary()

Model: "sequential_8"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_32 (Dense)            (None, 1)                 4         
                                                                 
 dense_33 (Dense)            (None, 256)               512       
                                                                 
 dense_34 (Dense)            (None, 128)               32896     
                                                                 
 dense_35 (Dense)            (None, 1)                 129       
                                                                 
Total params: 33,541
Trainable params: 33,541
Non-trainable params: 0
_________________________________________________________________


In [74]:
model.compile(optimizer='sgd',
              loss='binary_crossentropy',
              metrics=['accuracy'])

In [92]:
X = np.array(data_df[["Country", "Age", "Salary"]])

type(X)

numpy.ndarray

In [103]:
Y = np.array(data_df["Purchased"])

In [104]:
Y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1], dtype=object)

In [108]:
X = tf.convert_to_tensor(X, float)
Y = tf.convert_to_tensor(Y, float)
print(X, Y)

tf.Tensor(
[[1.         0.88       0.8674699 ]
 [0.6666667  0.54       0.57831323]
 [0.33333334 0.6        0.6506024 ]
 [0.6666667  0.76       0.73493975]
 [0.33333334 0.8        0.7684096 ]
 [1.         0.7        0.6987952 ]
 [0.6666667  0.78       0.62650603]
 [1.         0.96       0.9518072 ]
 [0.33333334 1.         1.        ]
 [1.         0.74       0.8072289 ]], shape=(10, 3), dtype=float32) tf.Tensor([0. 1. 0. 0. 1. 1. 0. 1. 0. 1.], shape=(10,), dtype=float32)


In [75]:
X = data_df.iloc[:, 0:3].values
Y = data_df.iloc[:, 3].values

m, n = X.shape

In [98]:
print(X)

[[1.0 0.88 0.8674698795180723]
 [0.6666666666666666 0.54 0.5783132530120482]
 [0.3333333333333333 0.6 0.6506024096385542]
 [0.6666666666666666 0.76 0.7349397590361446]
 [0.3333333333333333 0.8 0.7684096385542168]
 [1.0 0.7 0.6987951807228916]
 [0.6666666666666666 0.78 0.6265060240963856]
 [1.0 0.96 0.9518072289156626]
 [0.3333333333333333 1.0 1.0]
 [1.0 0.74 0.8072289156626506]]


array([[[[1.0, 0.88, 0.8674698795180723]]]], dtype=object)

In [77]:
type(Y)

numpy.ndarray

In [110]:
model.fit(X, Y, epochs=5000)

Epoch 1/1000
1/1 [==============================] - 0s 8ms/step - loss: 0.6910 - accuracy: 0.5000
Epoch 2/1000
1/1 [==============================] - 0s 7ms/step - loss: 0.6909 - accuracy: 0.5000
Epoch 3/1000
1/1 [==============================] - 0s 6ms/step - loss: 0.6909 - accuracy: 0.5000
Epoch 4/1000
1/1 [==============================] - 0s 6ms/step - loss: 0.6909 - accuracy: 0.5000
Epoch 5/1000
1/1 [==============================] - 0s 5ms/step - loss: 0.6909 - accuracy: 0.5000
Epoch 6/1000
1/1 [==============================] - 0s 6ms/step - loss: 0.6908 - accuracy: 0.5000
Epoch 7/1000
1/1 [==============================] - 0s 6ms/step - loss: 0.6908 - accuracy: 0.5000
Epoch 8/1000
1/1 [==============================] - 0s 7ms/step - loss: 0.6908 - accuracy: 0.5000
Epoch 9/1000
1/1 [==============================] - 0s 4ms/step - loss: 0.6908 - accuracy: 0.5000
Epoch 10/1000
1/1 [==============================] - 0s 5ms/step - loss: 0.6907 - accuracy: 0.5000
Epoch 11/1000
1/1 [

In [59]:
print(X[0:5])

[[1.0 0.88 0.8674698795180723]
 [0.6666666666666666 0.54 0.5783132530120482]
 [0.3333333333333333 0.6 0.6506024096385542]
 [0.6666666666666666 0.76 0.7349397590361446]
 [0.3333333333333333 0.8 0.7684096385542168]]


In [35]:
data_df.iloc[:, 3].values

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1], dtype=object)